### ISSUE TITLE
Add lpsolve based solver

### ISSUE THREAD

**Issue by jetuk** [snorfalorpagus/pywr#52]
An alternative to GLPK. Licence is LGPL, so that is OK?

It is also thread safe. 

http://lpsolve.sourceforge.net/5.5/

**Comment by snorfalorpagus** [comment]
Yes, LGPL is GPL-compatible. When you use it, you're effectively re-licencing the library (lpsolve) as GPL.

It will be interesting to see how lpsolve performs compared to GLPK. I know it didn't do so well for some of the other problems we've worked with, but these networked flow problems are a different beast (small and fast).

Since f79bf5f Travis will run the tests against multiple solvers (provided you add the appropriate environment variable in `.travis.yml`.
